name: PR Workflow

on:
  workflow_dispatch:

jobs:
  changedfolders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.changes.outputs.folders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed folders
        id: changes
        run: |
          echo "::set-output name=folders::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs -I{} dirname {} | sort -u)"
