name: Find Changed Folders

on:
  pull_request:
    paths:
      - 'Modules/**'
      - 'Resource Usage/**'

jobs:
  find-changed-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Find Changed Folders in Modules
        id: changed_folders_modules
        run: |
          base_commit=$(git merge-base HEAD ${{ github.base_ref }})
          changed_folders_modules=$(git diff --name-only $base_commit HEAD -- 'Modules/')
          echo "changed_folders_modules=${changed_folders_modules}" >> $GITHUB_OUTPUT

      - name: Find Changed Folders in Resource Usage
        id: changed_folders_resource
        run: |
          base_commit=$(git merge-base HEAD ${{ github.base_ref }})
          changed_folders_resource=$(git diff --name-only $base_commit HEAD -- 'Resource Usage/')
          echo "changed_folders_resource=${changed_folders_resource}" >> $GITHUB_OUTPUT

      - name: Display Changed Folders in Modules
        run: |
          changed_folders_modules="${{ steps.changed_folders_modules.outputs.changed_folders_modules }}"
          echo "Changed folders in 'Modules/':"
          echo "$changed_folders_modules"

      - name: Display Changed Folders in Resource Usage
        run: |
          changed_folders_resource="${{ steps.changed_folders_resource.outputs.changed_folders_resource }}"
          echo "Changed folders in 'Resource Usage/':"
          echo "$changed_folders_resource"
