name: PR Workflow

on:
  workflow_dispatch:

jobs:
  changedfolders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.changes.outputs.folders }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.2

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "$file was added"
          done
