name: PR Workflow

on:
  workflow_dispatch:

jobs:
  tfvars-copy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: Stockopedia/action-get-changed-files@v1
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        foldersOnly: true # to only include folders in the output

    - name: Echo
      run: echo ${{ steps.get_changed.outputs.changed }}
    
