name: Find Changed Files in PR
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  find-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Find Changed Files
        id: changed-files
        working-directory: /home/runner/work/GHActions/GHActions
        run: |
          git branch
          
