name: KICS Scan and Terraform Format Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  kics-scan-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Install KICS
      - name: Install KICS
        run: curl -sSfL https://get.kics.io | sh

      # Step 2: Get a list of changed modules in the PR
      - name: Get changed modules
        id: changed-modules
        run: |
          CHANGED_MODULES=($(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '^Modules/' | cut -d'/' -f 2 | uniq))
          echo "::set-output name=changed-modules::${CHANGED_MODULES[@]}"

      # Step 3: Copy .tfvars files for changed modules
      - name: Copy .tfvars files
        run: |
          CHANGED_MODULES=(${{ steps.changed-modules.outputs.changed-modules }})
          if [ -n "$CHANGED_MODULES" ]; then
            for module in "${CHANGED_MODULES[@]}"; do
              echo "Copying .tfvars files for module: $module"
              cp "Resource usage/$module"/*.tfvars "Modules/$module"/
            done
          else
            echo "No changed modules found in the PR."
          fi

      # Step 4: Run KICS Scan for changed modules
      - name: Run KICS Scan for changed modules
        uses: actions/checkout@v3
      - name: Run KICS Scan
        run: |
          CHANGED_MODULES=(${{ steps.changed-modules.outputs.changed-modules }})
          if [ -n "$CHANGED_MODULES" ]; then
            for module in "${CHANGED_MODULES[@]}"; do
              echo "Scanning module: $module"
              kics scan -p "Modules/$module" || exit 1
            done
          else
            echo "No changed modules found in the PR."
          fi

      # Step 5: Check Terraform format on changed modules
      - name: Check Terraform format on changed modules
        run: |
          CHANGED_MODULES=(${{ steps.changed-modules.outputs.changed-modules }})
          if [ -n "$CHANGED_MODULES" ]; then
            for module in "${CHANGED_MODULES[@]}"; do
              echo "Checking Terraform format in module: $module"
              terraform fmt -check "Modules/$module" || exit 1
            done
          else
            echo "No changed modules found in the PR."
          fi
