name: Find Changed Files in PR
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  find-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
          
      - name: Find Changed Files
        id: changed-files
        env:
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}  
        run: |
          git branch
          changed_files_module= `gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/Ved96/GHActions/pulls/$PR_NUMBER/files`

          
