name: Find Changed Files in PR
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  find-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
          
      - name: Find Changed Files
        id: changed-files
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITACTIONS }}
          SOURCE_BRANCH: ${{ github.base_ref }}
          TARGET_BRANCH: ${{ github.head_ref }}
        run: |
          echo $PR_NUMBER
          changed_files_module= `gh pr view $PR_NUMBER --json files --jq '.files.[].path'`
          echo $changed_files_module

          
