name: Find Changed Files in PR
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  find-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN}}
      - name: Checkout PR
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: 99
          
      - name: Find Changed Files
        id: changed-files
        working-directory: /home/runner/work/GHActions/GHActions
        run: |
          git branch
          changed_files_module=`git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)`
          changed_files_resource=`git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- 'Resource usage/'`
          echo $changed_files_module
          echo $changed_files_resource
