name: Find Changed Files in PR

on:
  workflow_dispatch:

jobs:
  find-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find Changed Files
        id: changed-files
        run: |
          base_branch="${{ github.event.pull_request.base.ref }}"
          pr_branch="${{ github.event.pull_request.head.ref }}"
          changed_files_module="$(git diff $base_branch $pr_branch -- Modules/)"
          changed_files_resource="$(git diff $base_branch $pr_branch -- Resource usage/)"
          echo "changed_files_folder1=${changed_files_folder1}" >> $GITHUB_OUTPUT
          echo "changed_files_folder2=${changed_files_folder2}" >> $GITHUB_OUTPUT

      - name: Print Changed Files
        run: |
          echo "Changed files in folder1: $changed_files_module"
          echo "Changed files in folder2: $changed_files_resource"

      - name: Print Changed Files
        env:
          changed_files_folder1: ${{ steps.changed-files.outputs.changed_files_folder1 }}
        run: echo "$changed_files_folder1"   
